### ISSUE TITLE
TabularGrid on frontend / PageController

### ISSUE THREAD

**Issue by silverstripesk** [lekoala/silverstripe-tabulator#1]
Is it possible to use TabularGrid directly in PageController? As I see (getCompatLayer() method), controller with form should extend LeftAndMain (Silverstripe's or Admini's).

I need CRUD dataobjects on frontend. I created Form with TabularGrid in PageController, I can see list of items, but editing causes error because getCompatLayer returns null in such usecase.

Thanks for help.

**Comment by lekoala** [comment]
i've never tried so far but it should work as long as you provide the compatLayer to set icons, button styles etc

just extend the CompatLayerInterface and you should be good to go

let me know if you find any issue

**Comment by silverstripesk** [comment]
I ended with custom tabular implementation, adding your module to PageController was too tricky.
